name       : ddcutil
version    : 0.9.1
release    : 1
source     :
    - https://www.ddcutil.com/tarballs/ddcutil-0.9.1.tar.gz : 6033763685a658c0fbebdf1eeae2b36e489a2db215b8ee4c53769709ffa88bac
license    : GPL-2.0-or-later
component  : system.utils
summary    : Query and change Linux monitor settings using DDC/CI and USB
description: |
    ddcutil is a program for querying and changing monitor settings, such as brightness and color levels.

    ddcutil uses DDC/CI to communicate with monitors implementing MCCS (Monitor Control Command Set) over I2C. Normally, the video driver for the monitor exposes the I2C channel as devices named /dev/i2c-n. There is also psupport for monitors (such as Apple Cinema and Eizo ColorEdge) that implement MCCS using a USB connection.

    A particular use case for ddcutil is as part of color profile management. Monitor calibration is relative to the monitor color settings currently in effect, e.g. red gain. ddcutil allows color related settings to be saved at the time a monitor is calibrated, and then restored when the calibration is applied.
builddeps  :
    - pkgconfig(libusb)
    - pkgconfig(x11)
    - pkgconfig(xrandr)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
