name       : ddcutil
version    : 1.4.1
release    : 7
source     :
    - https://github.com/rockowitz/ddcutil/archive/v1.4.1.tar.gz : c591891a1d2d950315b9ef50598f66bdd9951a51828328542ec36a0db0cb9edb
license    : GPL-2.0-or-later
component  : system.utils
summary    : Query and change Linux monitor settings using DDC/CI and USB
description: |
    ddcutil is a program for querying and changing monitor settings, such as brightness and color levels.

    ddcutil uses DDC/CI to communicate with monitors implementing MCCS (Monitor Control Command Set) over I2C. Normally, the video driver for the monitor exposes the I2C channel as devices named /dev/i2c-n. There is also psupport for monitors (such as Apple Cinema and Eizo ColorEdge) that implement MCCS using a USB connection.

    A particular use case for ddcutil is as part of color profile management. Monitor calibration is relative to the monitor color settings currently in effect, e.g. red gain. ddcutil allows color related settings to be saved at the time a monitor is calibrated, and then restored when the calibration is applied.
builddeps  :
    - pkgconfig(libkmod)
    - pkgconfig(libusb)
    - pkgconfig(xrandr)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install

    # Load i2c-dev by default
    install -Dm 00644 $pkgfiles/ddcutil.conf $installdir/%libdir%/modules-load.d/ddcutil.conf
